### ISSUE TITLE
Deploying to remote node

### ISSUE THREAD

**Issue by tarrencev** [gakonst/dapptools-template#10]
Hey guys,

Thanks for putting this together. I'm new to dapptools and this is a great starting point. I'm having some issues deploying to a remote node though. I run deploy like
```
ETH_FROM=0x35754fd45136f2a9996a75cf2955315c9cd35054 make deploy-rinkeby
```

Locally I get:
```
--rpc-url https://eth-rinkeby.alchemyapi.io/v2/***
curl: (22) The requested URL returned error: 400
```

On Alchemy it shows the failed request:
```
{"jsonrpc": "2.0", "id": 1, "error": {"code": -32601, "message": "Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys. See available methods at https://docs.alchemy.com/alchemy/documentation/apis"}}
```

Any ideas what I might be doing wrong? I imported the account using `ethsign`. 

As another note: When I run `ethsign` it lists an account but the address is different from MM. I tried reimporting for sanity and it says the account already exists. I guess it is using a different derivation path? I tried using that address as from but it fails too.

**Comment by d-xo** [comment]
Do you have `ETH_RPC_ACCOUNTS` set?

Are you using the latest dapptools release?

**Comment by ezynda3** [comment]
I'm having the same issue. No `ETH_RPC_ACCOUNTS` is set.

**Comment by tarrencev** [comment]
> Do you have `ETH_RPC_ACCOUNTS` set?
> 
> Are you using the latest dapptools release?

I believe `ETH_RPC_ACCOUNTS` is set by `.dapprc`. It's using the `dapptools` configured in `shell.nix`: https://github.com/gakonst/dapptools-template/blob/master/shell.nix#L5

**Comment by gakonst** [comment]
Updated version [here](https://github.com/gakonst/dapptools-template/commit/ba60b23502223bc706cdf2ff1ff0a57dfa5cf451) in case that was the issue. Can you please re-test? I am not experiencing this error.

**Comment by transmissions11** [comment]
hmm `shell.nix` does not determine the dapptools version you use on your local machine, only in nix-shell

make sure you actually install the latest dapptools with either the installer or [duppgrade](https://github.com/Rari-Capital/duppgrade)

**Comment by tarrencev** [comment]
hmm interesting. this is what i'm running, i can try with 0.34.1.

```
dapp --version
dapp 0.34.0
solc, the solidity compiler commandline interface
Version: 0.8.6+commit.11564f7e.Darwin.appleclang
hevm 0.48.0
```

but here is something a bit weird:

I try to import an account from metamask and don't set a password. On import is echos `35754fd45136f2a9996a75cf2955315c9cd35054` which corresponds to the metamask created account address. But when running `ethsign ls` it outputs a different address. Additionally, if it try sign a message using `seth` with the account and no pass it fails.

```
> ethsign import --keystore ~/.eth_keystore
Private key as 64 hexadecimal digits (not echoed): 
Choose a passphrase (not echoed): **no password provided**
35754fd45136f2a9996a75cf2955315c9cd35054
> ethsign ls                               
0xf28e313B87BFD2c8f7aa9880fFAfF299db94Cb96 keystore
> ETH_FROM=0xf28e313B87BFD2c8f7aa9880fFAfF299db94Cb96 seth sign "0xbeef"
Ethereum account passphrase (not echoed): could not decrypt key with given password **no password provided**
```

**Comment by transmissions11** [comment]
> hmm interesting. this is what i'm running, i can try with 0.34.1.

oo yes that's probably it. @gakonst's PR to override ETH_RPC_ACCOUNTS if ETH_FROM is in your keystore was just introduced in the latest update (0.3.4.1)

<img width="907" alt="Screen Shot 2021-09-11 at 3 03 35 PM" src="https://user-images.githubusercontent.com/26209401/132962650-b8ee9a30-aa2f-49a7-bb65-fbbdf64e5b01.png">

**Comment by transmissions11** [comment]
> I try to import an account from metamask and don't set a password. On import is echos 35754fd45136f2a9996a75cf2955315c9cd35054 which corresponds to the metamask created account address. But when running ethsign ls it outputs a different address. Additionally, if it try sign a message using seth with the account and no pass it fails.

Are you sure you're setting the keystore directory the same one you imported that new key in?

**Comment by tarrencev** [comment]
ah ok got it! also i figured out that `ethsign ls` was defaulting to a keystore parity previously configured 🤦‍♂️

**Comment by tarrencev** [comment]
okay all good now thanks! something to note is the dapp installer is still distributing `0.34.0` but duppgrade did the job!

```
> ETH_FROM=0x35754FD45136F2a9996a75Cf2955315C9Cd35054 ETH_KEYSTORE=~/.eth_keystore  seth sign "0xbeef"
Ethereum account passphrase (not echoed): 
0x94bc3f248eea93df8c2e4ad75599a9992176a7f279cc241ff29c51a034e967ed0cf7b9183edc2004ed146d48fb885cd944cca1f815621d50ae754ae51e2d8b001c
```

**Comment by transmissions11** [comment]
> okay all good now thanks! something to note is the dapp installer is still distributing `0.34.0` but `duppgrade` did the job!

ah yikes you're right! will bring up

**Comment by gakonst** [comment]
gg - good to hear it got resolved.

**Comment by d-xo** [comment]
@tarrencev thanks for pointing this out re: the installer. It's a little unfortunante, but it's just a cosmetic issue, and in general a weird little artefact from our release process.

It seems as though github has decided that `hevm/0.48.1` is the latest release instead of `dapp/0.34.1` as I wanted. The only difference between these two commits is that `dapp` and `seth` have incremented version numbers in the later, the versions of `dapp` and `seth` in the `hevm/0.48.1` tag otherwise behave exactly the same.
