### ISSUE TITLE
make test throwing nix permissions issue

### ISSUE THREAD

**Issue by namrapatel** [gakonst/dapptools-template#33]
Hello, I've been working on a new test implementation and every time I try to run `make test`, this is the error result I'm given:

dapp test # --ffi # enable if you need the `ffi` cheat code on HEVM
dapp---use: Could not find solc-0.8.7 in your path or nix store.
Temporarily installing solc-0.8.7...
Tip: run `nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_7` for a lasting installation of this version.
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
make: *** [test] Error 1

I've tried using chmod to change the permissions on the /nix directory myself, but it doesn't seem to work. Perhaps this issue is simply on my end and has nothing to do with this template, but I thought I'd post here to see if anyone has any ideas anyways.

**Comment by transmissions11** [comment]
this sounds like an issue you should file in the [dapptools repo](https://github.com/dapphub/dapptools) :p

**Comment by namrapatel** [comment]
Haha fair enough, anyhow, the issue was solved by uninstalling nix and reinstalling nix + dapptools from scratch. 

This link: https://discourse.nixos.org/t/help-fixing-macos-catalina-install/7900/4 helped me uninstall Nix, it wasn't working before, giving me "permission denied" errors.
